import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Header } from "./_components";
import { PREFIX } from "./_utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: PREFIX + 'tan tran',
  description: "Generated by create next app by " + PREFIX + 'tan tran',
};

export default function RootLayout({
  children,
}: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
